{
    "cveId": "CVE-2021-3116",
    "version": "1.0.0",
    "timestamp": "2024-12-13T17:34:55.850537+00:00",
    "description": "before_upstream_connection in AuthPlugin in http/proxy/auth.py in proxy.py before 2.3.1 accepts incorrect Proxy-Authorization header data because of a boolean confusion (and versus or).",
    "keyphrases": {
        "rootcause": "boolean confusion",
        "weakness": "",
        "impact": "",
        "vector": "incorrect Proxy-Authorization header data",
        "attacker": "",
        "product": "http/proxy/auth.py in proxy.py",
        "version": "before 2.3.1",
        "component": "before_upstream_connection in AuthPlugin"
    }
}
