{
    "cveId": "CVE-2020-24372",
    "version": "1.0.0",
    "timestamp": "2024-12-13T17:34:55.850537+00:00",
    "description": "LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in lj_err.c.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "out-of-bounds read",
        "impact": "",
        "vector": "",
        "attacker": "",
        "product": "LuaJIT",
        "version": "through 2.1.0-beta3",
        "component": "lj_err_run in lj_err.c"
    }
}
