{
    "cveId": "CVE-2021-37644",
    "version": "1.0.0",
    "timestamp": "2024-12-15T20:24:27.876763+00:00",
    "description": "TensorFlow is an end-to-end open source platform for machine learning. In affected versions providing a negative element to `num_elements` list argument of `tf.raw_ops.TensorListReserve` causes the runtime to abort the process due to reallocating a `stdvector` to have a negative number of elements. The [implementation](https//github.com/tensorflow/tensorflow/blob/8d72537c6abf5a44103b57b9c2e22c14f5f49698/tensorflow/core/kernels/list_kernels.cc#L312) calls `stdvector.resize()` with the new size controlled by input given by the user, without checking that this input is valid. We have patched the issue in GitHub commit 8a6e874437670045e6c7dc6154c7412b4a2135e2. The fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "providing a negative element to num_elements list argument of tf.raw_ops.TensorListReserve",
        "impact": "runtime to abort the process due to reallocating a stdvector to have a negative number of elements",
        "vector": "",
        "attacker": "",
        "product": "TensorFlow",
        "version": [
            "versions prior to 2.6.0",
            "2.5.1",
            "2.4.3",
            "2.3.4"
        ],
        "component": "tf.raw_ops.TensorListReserve"
    }
}
