{
  "cveId": "CVE-2021-4118",
  "version": "1.0.0",
  "timestamp": "2024-12-15T20:24:27.876763+00:00",
  "description": "pytorch-lightning is vulnerable to Deserialization of Untrusted Data",
  "keyphrases": {
    "rootcause": [
      "Deserialization of Untrusted Data",
      "improper deserialization"
    ],
    "weakness": "Deserialization",
    "impact": "",
    "vector": "",
    "attacker": "",
    "product": "pytorch-lightning",
    "version": "",
    "component": ""
  },
  "mitreTechnicalImpacts": []
}