{
    "cveId": "CVE-2024-45230",
    "version": "1.0.0",
    "timestamp": "2024-12-06T11:32:07.789868+00:00",
    "description": "An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "",
        "impact": "denial-of-service attack",
        "vector": "very large inputs with a specific sequence of characters",
        "attacker": "",
        "product": "Django",
        "version": "5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16",
        "component": "urlize() and urlizetrunc() template filters"
    }
}
