{
  "cveId": "CVE-2024-41990",
  "version": "1.0.0",
  "timestamp": "2024-12-06T11:32:07.789868+00:00",
  "description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
  "keyphrases": {
    "rootcause": "",
    "weakness": "potential denial-of-service attack",
    "impact": [
      "denial of service",
      "denial-of-service attack"
    ],
    "vector": "very large inputs with a specific sequence of characters",
    "attacker": "",
    "product": "Django",
    "version": "5.0 before 5.0.8 and 4.2 before 4.2.15",
    "component": "['urlize() and urlizetrunc() template filters']"
  },
  "mitreTechnicalImpacts": []
}