{
    "cveId": "CVE-2019-16227",
    "version": "1.0.0",
    "timestamp": "2024-12-12T22:08:52.294043+00:00",
    "description": "An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE this outcome occurs when accessing a data.mdb file supplied by an attacker.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "memcpy with an invalid write operation",
        "impact": "access data in memory that is outside the bounds of the intended array",
        "vector": "accessing a data.mdb file supplied by an attacker",
        "attacker": "",
        "product": "py-lmdb",
        "version": "0.97",
        "component": "mdb_cursor_set"
    }
}
