{
    "cveId": "CVE-2008-7264",
    "version": "1.0.0",
    "timestamp": "2024-12-10T17:54:04.992951+00:00",
    "description": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "file descriptor exhaustion",
        "impact": "denial of service",
        "vector": "QUIT command during a disallowed data-transfer attempt",
        "attacker": "remote authenticated users",
        "product": "pyftpdlib",
        "version": "before 0.5.0",
        "component": "ftp_QUIT function in ftpserver.py"
    }
}
