{
    "cveId": "CVE-2025-48432",
    "version": "1.0.0",
    "timestamp": "2025-07-04T16:12:41.853043+00:00",
    "description": "An issue was discovered in Django 5.2 before 5.2.3, 5.1 before 5.1.11, and 4.2 before 4.2.23. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "",
        "impact": "log injection or forgery",
        "vector": "crafted URLs",
        "attacker": "remote attackers",
        "product": "Django",
        "version": [
            "['5.2 before 5.2.3'",
            "'5.1 before 5.1.11'",
            "'4.2 before 4.2.23']"
        ],
        "component": "Internal HTTP response logging"
    }
}
