{
    "cveId": "CVE-2020-15523",
    "version": "1.0.0",
    "timestamp": "2024-12-13T17:34:55.850537+00:00",
    "description": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
    "keyphrases": {
        "rootcause": "invalid search path for python3.dll loading",
        "weakness": "",
        "impact": "use Trojan horse python3.dll",
        "vector": "",
        "attacker": "",
        "product": "Python",
        "version": "3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4",
        "component": "CPython on Windows"
    }
}
