{
    "cveId": "CVE-2020-15168",
    "version": "1.0.0",
    "timestamp": "2024-12-13T17:34:55.850537+00:00",
    "description": "node-fetch before versions 2.6.1 and 3.0.0-beta.9 did not honor the size option after following a redirect, which means that when a content size was over the limit, a FetchError would never get thrown and the process would end without failure. For most people, this fix will have a little or no impact. However, if you are relying on node-fetch to gate files above a size, the impact could be significant, for example If you dont double-check the size of the data after fetch() has completed, your JS thread could get tied up doing work on a large file (DoS) and/or cost you money in computing.",
    "keyphrases": {
        "rootcause": "did not honor the size option after following a redirect",
        "weakness": "",
        "impact": [
            "FetchError would never get thrown",
            "process would end without failure"
        ],
        "vector": "",
        "attacker": "",
        "product": "node-fetch",
        "version": "before versions 2.6.1 and 3.0.0-beta.9",
        "component": ""
    }
}
