{
    "cveId": "CVE-2022-29204",
    "version": "1.0.0",
    "timestamp": "2024-11-03T18:37:50.907685+00:00",
    "description": "TensorFlow is an open source platform for machine learning. Prior to versions 2.9.0, 2.8.1, 2.7.2, and 2.6.4, the implementation of `tf.raw_ops.UnsortedSegmentJoin` does not fully validate the input arguments. This results in a `CHECK`-failure which can be used to trigger a denial of service attack. The code assumes `num_segments` is a positive scalar but there is no validation. Since this value is used to allocate the output tensor, a negative value would result in a `CHECK`-failure (assertion failure), as per TFSA-2021-198. Versions 2.9.0, 2.8.1, 2.7.2, and 2.6.4 contain a patch for this issue.",
    "keyphrases": {
        "rootcause": "missing input validation",
        "weakness": "",
        "impact": "denial of service",
        "vector": "negative value for num_segments",
        "attacker": "",
        "product": "TensorFlow",
        "version": "prior to 2.9.0, 2.8.1, 2.7.2, and 2.6.4",
        "component": "tf.raw_ops.UnsortedSegmentJoin"
    },
    "mitreTechnicalImpacts": [
        "Denial-of-Service: resource consumption",
        "Denial-of-Service: unreliable execution"
    ]
}
