{
    "cveId": "CVE-2022-41323",
    "version": "1.0.0",
    "timestamp": "2024-12-15T20:24:27.876763+00:00",
    "description": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.",
    "keyphrases": {
        "rootcause": "",
        "weakness": "regular expression denial of service",
        "impact": "denial of service",
        "vector": "locale parameter",
        "attacker": "",
        "product": "Django",
        "version": [
            "3.2 before 3.2.16",
            "4.0 before 4.0.8",
            "4.1 before 4.1.2"
        ],
        "component": "internationalized URLs"
    }
}
