{
    "cveId": "CVE-2024-42252",
    "version": "1.0.0",
    "timestamp": "2024-12-17T08:36:27.567979+00:00",
    "description": "In the Linux kernel, the following vulnerability has been resolvedclosures Change BUG_ON() to WARN_ON()If a BUG_ON() can be hit in the wild, it shouldnt be a BUG_ON()For reference, this has popped up once in the CI, and well need moreinfo to debug it03240 ------------[ cut here ]------------03240 kernel BUG at lib/closure.c21!03240 kernel BUG at lib/closure.c21!03240 Internal error Oops - BUG 00000000f2000800",
    "keyphrases": {
        "rootcause": "BUG_ON() assertion hit",
        "weakness": "",
        "impact": "kernel panic",
        "vector": "",
        "attacker": "",
        "product": "Linux kernel",
        "version": "",
        "component": "lib/closure.c"
    }
}
